apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: nikithamanvi/healthcare:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
