# Healthcare_Project.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject-healthcare
  labels:
    app: myproject-healthcare-lbl
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: medicure
          image: niki/healthcare:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
  selector:
    matchLabels:
      app: healthcare
---
apiVersion: v1
kind: Service
metadata:
  name: myproject-healthcare-service
  labels:
    app: myproject-healthcare-lbl
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31039
